apiVersion: v1
name: autobot # This value was modified by the initial-setup python script
description: A Helm chart for deploying autobot-frontend. # This value was modified by the initial-setup python script
version: 1.0
