appName: autobot-backend # This value was modified by the initial-setup python script

deployment:
  image:
    repository: korize/autobot-backend # This value was modified by the initial-setup python script